Vagrant.configure("2") do |config|

  # Base box creation
  config.vm.define "basebox" do |base|
    base.vm.box = "opensuse/Leap-15.5.aarch64"

    # Use qemu
    base.vm.provider "qemu" do |qemu|
      qemu.qemu_binary = "/usr/local/bin/qemu-system-aarch64"
      qemu.qemu_dir    = "/usr/local/share/qemu"
      qemu.memory      = 2048
      qemu.cpus        = 2
      qemu.disk_size   = "20G"
      qemu.machine     = "virt,accel=hvf,highmem=off"
      qemu.arch        = "aarch64"
      qemu.cpu         = "host"
    end

    # SSH config
    base.ssh.username = "vagrant"
    base.ssh.insert_key = false

    base.vm.provision "shell", inline: <<-SHELL
      echo 'Installing WireGuard'
      zypper refresh
      zypper -n install wireguard-tools iptables

      echo 'Downloading k3s installation script'
      curl -o /usr/local/bin/k3s_install.sh -sfL https://get.k3s.io
      chmod +x /usr/local/bin/k3s_install.sh

      echo 'Downloading HashiCorp Nomad'
      zypper -n install wget unzip
      wget https://releases.hashicorp.com/nomad/1.8.2/nomad_1.8.2_linux_arm64.zip
      unzip nomad_1.8.2_linux_arm64.zip
      sudo mv nomad /usr/local/bin/
    SHELL
  end

#  config.vm.box = "custom-opensuse-leap15.5.aarch64"

  def configure_vm(vm, vm_name, ssh_port, wireguard_conf, provision_command)
    vm.vm.box = "custom-opensuse-leap-15-5.aarch64"

    vm.vm.provider "qemu" do |qemu|
      qemu.qemu_binary = "/usr/local/bin/qemu-system-aarch64"
      qemu.qemu_dir    = "/usr/local/share/qemu"
      qemu.memory      = 2048
      qemu.cpus        = 2
      qemu.disk_size   = "20G"
      qemu.machine     = "virt,accel=hvf,highmem=off"
      qemu.arch        = "aarch64"
      qemu.cpu         = "host"
      qemu.ssh_port    = ssh_port
    end

    vm.ssh.username   = "vagrant"
    vm.ssh.insert_key = false

    # Shell provision for VM
    vm.vm.provision "shell", inline: <<-SHELL
      echo 'Configuring WireGuard with #{wireguard_conf}'
      sudo mkdir -p /etc/wireguard
      sudo cp /vagrant/wireguard-configs/#{wireguard_conf} /etc/wireguard/wg0.conf
      sudo chmod 600 /etc/wireguard/wg0.conf
      sudo wg-quick up wg0

      echo 'Running #{provision_command} installation'
      #{provision_command}
    SHELL
  end

  vms = [
    {name: "k3s-vm", port: 50023, wireguard: "wg0-vm1.conf", command: "/usr/local/bin/k3s_install.sh"},
    {name: "nomad-vm1", port: 50024, wireguard: "wg0-vm2.conf", command: "sudo nomad agent -dev"},
    {name: "nomad-vm2", port: 50025, wireguard: "wg0-vm3.conf", command: "sudo nomad agent -dev"},
    {name: "nomad-vm3", port: 50026, wireguard: "wg0-vm4.conf", command: "sudo nomad agent -dev"}
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      configure_vm(node, vm[:name], vm[:port], vm[:wireguard], vm[:command])
    end
  end
end


