---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if WireGuard is running
      become: yes
      shell: "wg show | grep -q interface"
      register: wg_status
      ignore_errors: true

    - name: Bring WireGuard VPN up with wg_setup.sh if WireGuard is not running
      become: yes
      shell: sh wg_setup.sh
      args:
        chdir: "{{ playbook_dir }}"
      when: wg_status.failed

    - name: Ensure VM ssh ports are available before proceeding
      shell: sh check_ports.sh
      args:
        chdir: "{{ playbook_dir }}"
      register: port_check_result
      failed_when: port_check_result.rc != 0

    - name: Check if the private SSH key for temp cluster exists
      stat:
        path: "{{ playbook_dir }}/ansible_key"
      register: ssh_private_key

    - name: Generate new SSH key pair if it does not exist
      command: ssh-keygen -t rsa -b 2048 -f {{ playbook_dir }}/ansible_key -N ""
      when: not ssh_private_key.stat.exists

    - name: Ensure Vagrant is up
      shell: vagrant up
      args:
        chdir: "{{ playbook_dir }}"
      register: vagrant_up_result
      ignore_errors: yes  # Continue even if Vagrant is already up

    - name: Display Vagrant up result
      debug:
        var: vagrant_up_result.stdout_lines

    - name: Check the status of Vagrant VMs
      shell: vagrant status
      args:
        chdir: "{{ playbook_dir }}"  # Ensures the command runs in the directory containing the Vagrantfile
      register: vagrant_status
      ignore_errors: yes

    - name: Display Vagrant status
      debug:
        var: vagrant_status.stdout_lines

    - name: Show the WireGuard VPN
      become: yes
      shell: "wg show"
      register: wg_status

    - name: Display Vagrant status
      debug:
        var: wg_status.stdout_lines

#########################        
# Lets setup the VMs now!
#########################        
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      zypper:
        name:
          - curl
          - wget
          - vim
          - docker
          - zip
          - unzip
          - bind-utils
          - podman
          - jq
          - hostname
        state: present

    - name: Ensure Podman service is started and enabled
      systemd:
        name: podman
        state: started
        enabled: yes

- hosts: k3s
  become: yes
  tasks:
    - name: Get IP address of the wg0 interface
      shell: ip -4 addr show wg0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
      register: wg0_ip

    - name: Set node_ip fact
      set_fact:
        node_ip: "{{ wg0_ip.stdout }}"

###############################################
# Lets move to setup all of the Nomad stuff now
###############################################
- hosts: nomad_server
  become: yes
  tasks:
    - name: Ensure volumes directory exists # TODO: figure out why directory is not created by service
      file:
        path: /tmp/nomad-slurmctl-volumes/log
        state: directory
        mode: '0755'

    - name: Set hostname
      ansible.builtin.hostname:
        name: "vm1" # TODO: lift from inventory

    - name: Download the Nomad Podman driver
      get_url:
        url: https://releases.hashicorp.com/nomad-driver-podman/0.6.1/nomad-driver-podman_0.6.1_linux_amd64.zip
        dest: /tmp/nomad-driver-podman.zip

    - name: Ensure the Nomad driver plugin directory exists
      file:
        path: /tmp/nomad-driver-plugin/plugin
        state: directory
        mode: '0755'

    - name: Unzip the Nomad Podman driver
      unarchive:
        src: /tmp/nomad-driver-podman.zip
        dest: /tmp/nomad-driver-plugin/plugin
        remote_src: yes

    - name: Install Nomad on server node
      get_url:
        url: https://releases.hashicorp.com/nomad/1.8.2/nomad_1.8.2_linux_amd64.zip
        dest: /tmp/nomad.zip

    - name: Unzip and install Nomad on server
      unarchive:
        src: /tmp/nomad.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Create Nomad configuration directory on server
      file:
        path: /etc/nomad.d
        state: directory
        mode: '0755'

    - name: Create Nomad certificates directory on server
      file:
        path: /etc/nomad.d/nomad_certificates
        state: directory
        mode: '0755'

    - name: Copy all Nomad certificates to server
      copy:
        src: "{{ item }}"
        dest: "/etc/nomad.d/nomad_certificates/"
        mode: '0644'
      with_fileglob:
        - "nomad_certificates/*.pem"

    - name: Generate Nomad server configuration file from template
      template:
        src: templates/server.hcl.j2
        dest: /etc/nomad.d/nomad.hcl
        mode: '0644'

    - name: Configure and start Nomad service on server
      template:
        src: templates/nomad.service.j2
        dest: /etc/systemd/system/nomad.service

    - name: Reload systemd to apply Nomad changes on server
      command: systemctl daemon-reload

    - name: Start and enable Nomad service on server
      systemd:
        name: nomad
        state: started
        enabled: yes

    - name: Wait for Nomad server to be ready
      wait_for:
        port: 4646
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 300

    - name: Generate the bootstrap management token
      command: /usr/local/bin/nomad acl bootstrap -json
      environment:
        NOMAD_ADDR: https://{{ inventory_hostname }}:4646
        NOMAD_CACERT: /etc/nomad.d/nomad_certificates/cluster.local-agent-ca.pem
        NOMAD_CLIENT_CERT: /etc/nomad.d/nomad_certificates/vm-cli-cluster.local.pem
        NOMAD_CLIENT_KEY: /etc/nomad.d/nomad_certificates/vm-cli-cluster.local-key.pem
        NOMAD_SKIP_VERIFY: "1"
      register: bootstrap_token

    - name: Display the bootstrap management token output
      debug:
        var: bootstrap_token.stdout

    - name: Set the bootstrap token as a fact
      set_fact:
        nomad_bootstrap_token: "{{ bootstrap_token.stdout | from_json }}"

    - name: Store the bootstrap management token locally
      delegate_to: localhost
      copy:
        content: "{{ bootstrap_token.stdout }}"
        dest: ./nomad_bootstrap_token.json
      become: no  # Make sure sudo is not used

