---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if WireGuard is running
      become: yes
      shell: "wg show | grep -q interface"
      register: wg_status
      ignore_errors: true

    - name: Bring WireGuard VPN up with wg_setup.sh if WireGuard is not running
      become: yes
      shell: sh wg_setup.sh
      args:
        chdir: "{{ playbook_dir }}"
      when: wg_status.failed

    - name: Ensure VM ssh ports are available before proceeding
      shell: sh check_ports.sh
      args:
        chdir: "{{ playbook_dir }}"
      register: port_check_result
      failed_when: port_check_result.rc != 0

    - name: Ensure Vagrant is up
      shell: vagrant up
      args:
        chdir: "{{ playbook_dir }}"
      register: vagrant_up_result
      ignore_errors: yes  # Continue even if Vagrant is already up

    - name: Display Vagrant up result
      debug:
        var: vagrant_up_result.stdout_lines

    - name: Check the status of Vagrant VMs
      shell: vagrant status
      args:
        chdir: "{{ playbook_dir }}"  # Ensures the command runs in the directory containing the Vagrantfile
      register: vagrant_status
      ignore_errors: yes

    - name: Display Vagrant status
      debug:
        var: vagrant_status.stdout_lines

    - name: Show the WireGuard VPN
      become: yes
      shell: "wg show"
      register: wg_status

    - name: Display Vagrant status
      debug:
        var: wg_status.stdout_lines

#########################        
# Lets setup the VMs now!
#########################        
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      zypper:
        name:
          - curl
          - wget
          - vim
          - docker
          - zip
          - unzip
        state: present

- hosts: k3s
  become: yes
  tasks:
    - name: Get IP address of the wg0 interface
      shell: ip -4 addr show wg0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
      register: wg0_ip

    - name: Set node_ip fact
      set_fact:
        node_ip: "{{ wg0_ip.stdout }}"

    - name: Install k3s on k3s node
      shell: curl -sfL https://get.k3s.io | sh -
      register: k3s_install_result
      retries: 5         # Number of retries
      delay: 30          # Wait 30 seconds between retries
      until: k3s_install_result.rc == 0

    - name: Generate k3s configuration file
      template:
        src: templates/k3s-config.yaml.j2  # Adjust this path to your actual template location if different
        dest: /etc/rancher/k3s/config.yaml
        mode: '0644'

    - name: Reload systemd to apply k3s changes
      command: systemctl daemon-reload

    - name: Restart k3s service
      systemd:
        name: k3s
        state: restarted
        enabled: yes

    - name: Install kubectl in k3s for testing
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/

    - name: Fetch kubeconfig directly to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s-{{ inventory_hostname }}.yaml
        flat: yes
        validate_checksum: no

    - name: Modify CoreDNS service to use LoadBalancer type
      shell: |
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml  /usr/local/bin/kubectl patch svc kube-dns -n kube-system -p '{"spec": {"type": "LoadBalancer"}}'
      register: patch_coredns

###################################################
# Set up k3s coreDNS as nameserver for all machines
###################################################
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get K3s VM IP from inventory
      set_fact:
        k3s_vm_ip: "{{ hostvars[groups['k3s'][0]]['inventory_hostname'] }}"

- hosts: all
  become: yes
  tasks:
    - name: Install bind-utils package (for nslookup and dig)
      zypper:
        name: bind-utils
        state: present

    - name: Add K3s VM IP to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ k3s_vm_ip }}"
        insertafter: "^nameserver"
        state: present

    - name: Ensure the resolv.conf is updated by netconfig
      shell: "netconfig update -f"
      args:
        warn: false

- hosts: nomad_server
  become: yes
  tasks:
    - name: Install Nomad on server node
      get_url:
        url: https://releases.hashicorp.com/nomad/1.8.2/nomad_1.8.2_linux_arm64.zip
        dest: /tmp/nomad.zip

    - name: Unzip and install Nomad on server
      unarchive:
        src: /tmp/nomad.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Create Nomad configuration directory on server
      file:
        path: /etc/nomad.d
        state: directory
        mode: '0755'

    - name: Generate Nomad server configuration file from template
      template:
        src: templates/server.hcl.j2
        dest: /etc/nomad.d/nomad.hcl
        mode: '0644'

    - name: Configure and start Nomad service on server
      template:
        src: templates/nomad.service.j2
        dest: /etc/systemd/system/nomad.service

    - name: Reload systemd to apply Nomad changes on server
      command: systemctl daemon-reload

    - name: Start and enable Nomad service on server
      systemd:
        name: nomad
        state: started
        enabled: yes

    - name: Wait for Nomad server to be ready
      wait_for:
        port: 4646
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 300

    - name: Generate the bootstrap management token
      command: /usr/local/bin/nomad acl bootstrap -json
      register: bootstrap_token

    - name: Set the bootstrap token as a fact
      set_fact:
        nomad_bootstrap_token: "{{ bootstrap_token.stdout | from_json }}"

    - name: Store the bootstrap management token locally
      delegate_to: localhost
      copy:
        content: "{{ bootstrap_token.stdout }}"
        dest: ./nomad_bootstrap_token.json
      become: no  # Make sure sudo is not used


- hosts: nomad_clients
  become: yes
  tasks:
    - name: Install Nomad on server node
      get_url:
        url: https://releases.hashicorp.com/nomad/1.8.2/nomad_1.8.2_linux_arm64.zip
        dest: /tmp/nomad.zip

    - name: Unzip and install Nomad on server
      unarchive:
        src: /tmp/nomad.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Create Nomad configuration directory on clients
      file:
        path: /etc/nomad.d
        state: directory
        mode: '0755'

    - name: Generate Nomad client configuration file from template
      template:
        src: templates/nomad.hcl.j2
        dest: /etc/nomad.d/nomad.hcl
        mode: '0644'

    - name: Generate and configure Nomad service file
      template:
        src: templates/nomad.service.j2
        dest: /etc/systemd/system/nomad.service
      vars:
        bootstrap_token: "{{ hostvars[groups['nomad_server'][0]].nomad_bootstrap_token.SecretID }}"

    - name: Reload systemd to apply Nomad changes on clients
      command: systemctl daemon-reload

    - name: Start and enable Nomad service on clients
      systemd:
        name: nomad
        state: started
        enabled: yes

